export type ID = string;
export type ISODateTime = string;
export type Money = { amount: number; currency: string };
export type PromotionStatus = "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | "ARCHIVED";
export type CouponStatus = "AVAILABLE" | "RESERVED" | "REDEEMED" | "EXPIRED" | "CANCELLED";
export type DiscountType = "FIXED" | "PERCENTAGE";
export type PromotionKind = "COUPON" | "AUTOMATIC" | "CAMPAIGN" | "BUNDLE" | "CUSTOM";
export type PromotionAction = "CREATE" | "ACTIVATE" | "PAUSE" | "RESUME" | "EXPIRE" | "ARCHIVE";
export type CouponAction = "ISSUE" | "RESERVE" | "REDEEM" | "RELEASE" | "EXPIRE" | "CANCEL";
export type PromotionSource = "ADMIN" | "SYSTEM" | "CAMPAIGN" | "API" | "IMPORT";
export interface DiscountRule { id: ID; promotionId: ID; type: DiscountType; value: number; currency?: string; maxDiscount?: Money; productIds?: ID[]; categoryIds?: ID[]; serviceIds?: ID[]; minimumSubtotal?: Money; maximumUses?: number; perCustomerLimit?: number; }
export interface Promotion { id: ID; tenantId: ID; code?: string; name: string; kind: PromotionKind; status: PromotionStatus; rules: DiscountRule[]; startsAt: ISODateTime; endsAt?: ISODateTime; priority: number; stackable: boolean; source: PromotionSource; createdAt: ISODateTime; updatedAt: ISODateTime; }
export interface Coupon { id: ID; tenantId: ID; promotionId: ID; code: string; status: CouponStatus; customerId?: ID; issuedAt: ISODateTime; reservedAt?: ISODateTime; redeemedAt?: ISODateTime; expiresAt?: ISODateTime; reservationReference?: ID; redemptionReference?: ID; }
export interface DiscountContext { tenantId: ID; customerId?: ID; currency: string; subtotal: Money; productIds?: ID[]; categoryIds?: ID[]; serviceIds?: ID[]; couponCode?: string; at: ISODateTime; existingPromotionIds?: ID[]; }
export interface DiscountResult { eligible: boolean; promotionId?: ID; couponId?: ID; discount: Money; reason?: string; ruleId?: ID; }
export interface PromotionEvent { id: ID; promotionId: ID; action: PromotionAction; occurredAt: ISODateTime; actorId?: ID; reason?: string; fromStatus?: PromotionStatus; toStatus?: PromotionStatus; }
export interface CouponEvent { id: ID; couponId: ID; action: CouponAction; occurredAt: ISODateTime; actorId?: ID; referenceId?: ID; }
export interface PromotionRepository { create(record: Promotion): Promise<Promotion>; getById(tenantId: ID, promotionId: ID): Promise<Promotion | null>; update(record: Promotion): Promise<Promotion>; list(query: { tenantId: ID; status?: PromotionStatus; code?: string }): Promise<Promotion[]>; }
export interface CouponRepository { create(record: Coupon): Promise<Coupon>; getById(tenantId: ID, couponId: ID): Promise<Coupon | null>; getByCode(tenantId: ID, code: string): Promise<Coupon | null>; update(record: Coupon): Promise<Coupon>; }
export interface PromotionEligibilityPort { check(context: DiscountContext, promotion: Promotion): Promise<{ eligible: boolean; reason?: string }>; }
export interface DiscountCalculationPort { calculate(context: DiscountContext, promotion: Promotion): Promise<DiscountResult>; }
export interface CouponValidationPort { validate(coupon: Coupon, context: DiscountContext): Promise<{ valid: boolean; errors: string[] }>; }
export interface PromotionActivationPolicy { isEnabled(tenantId: ID): Promise<boolean>; }
export interface PromotionAuditPort { record(event: PromotionEvent | CouponEvent): Promise<void>; }
export interface PromotionTelemetryPort { metric(name: string, value: number, dimensions?: Record<string, string>): void; }
export interface PromotionEventRepository { append(event: PromotionEvent): Promise<void>; }
export interface CouponEventRepository { append(event: CouponEvent): Promise<void>; }
export interface PromotionRedemptionPort { reserve(coupon: Coupon, referenceId: ID, at: ISODateTime): Promise<Coupon>; redeem(coupon: Coupon, referenceId: ID, at: ISODateTime): Promise<Coupon>; release(coupon: Coupon, at: ISODateTime): Promise<Coupon>; }
const SECRET_PATTERNS = [/password/i, /secret/i, /private[ _-]?key/i, /access[ _-]?token/i, /refresh[ _-]?token/i, /api[ _-]?key/i, /authorization/i, /cvv|cvc/i, /pan/i, /card[ _-]?number/i];
export function containsSensitiveKey(value: string): boolean { return SECRET_PATTERNS.some((pattern) => pattern.test(value)); }
export function validatePromotionInput(record: Promotion): string[] { const errors: string[] = []; if (!record.id) errors.push("promotion.id is required"); if (!record.tenantId) errors.push("promotion.tenantId is required"); if (!record.name.trim()) errors.push("promotion.name is required"); if (!record.rules.length) errors.push("promotion.rules must not be empty"); if (!Number.isInteger(record.priority)) errors.push("promotion.priority must be an integer"); for (const rule of record.rules) { if (!rule.id || rule.promotionId !== record.id) errors.push(`invalid rule ${rule.id || "unknown"}`); if (!Number.isFinite(rule.value) || rule.value < 0) errors.push(`invalid discount value for ${rule.id}`); if (rule.type === "PERCENTAGE" && rule.value > 100) errors.push(`percentage discount above 100 for ${rule.id}`); if (rule.type === "FIXED" && !rule.currency) errors.push(`currency is required for fixed discount ${rule.id}`); if (rule.currency && containsSensitiveKey(rule.currency)) errors.push(`sensitive key in currency for ${rule.id}`); } return errors; }
export function validateCouponInput(record: Coupon): string[] { const errors: string[] = []; if (!record.id) errors.push("coupon.id is required"); if (!record.tenantId) errors.push("coupon.tenantId is required"); if (!record.promotionId) errors.push("coupon.promotionId is required"); if (!record.code.trim()) errors.push("coupon.code is required"); if (containsSensitiveKey(record.code)) errors.push("coupon.code contains a sensitive pattern"); return errors; }
export function transitionPromotionStatus(current: PromotionStatus, action: PromotionAction): PromotionStatus | null { const map: Record<PromotionStatus, Partial<Record<PromotionAction, PromotionStatus>>> = { DRAFT: { ACTIVATE: "ACTIVE", ARCHIVE: "ARCHIVED" }, ACTIVE: { PAUSE: "PAUSED", EXPIRE: "EXPIRED", ARCHIVE: "ARCHIVED" }, PAUSED: { RESUME: "ACTIVE", EXPIRE: "EXPIRED", ARCHIVE: "ARCHIVED" }, EXPIRED: { ARCHIVE: "ARCHIVED" }, ARCHIVED: {} }; return map[current][action] ?? null; }
export function transitionCouponStatus(current: CouponStatus, action: CouponAction): CouponStatus | null { const map: Record<CouponStatus, Partial<Record<CouponAction, CouponStatus>>> = { AVAILABLE: { RESERVE: "RESERVED", REDEEM: "REDEEMED", EXPIRE: "EXPIRED", CANCEL: "CANCELLED" }, RESERVED: { REDEEM: "REDEEMED", RELEASE: "AVAILABLE", EXPIRE: "EXPIRED", CANCEL: "CANCELLED" }, REDEEMED: {}, EXPIRED: {}, CANCELLED: {} }; return map[current][action] ?? null; }
export async function evaluatePromotion(context: DiscountContext, promotion: Promotion, deps: { activation: PromotionActivationPolicy; eligibility: PromotionEligibilityPort; calculation: DiscountCalculationPort; audit: PromotionAuditPort; telemetry: PromotionTelemetryPort }): Promise<DiscountResult> { if (!(await deps.activation.isEnabled(context.tenantId))) return { eligible: false, discount: { amount: 0, currency: context.currency }, reason: "PROMOTION_FEATURE_DISABLED" }; if (promotion.status !== "ACTIVE") return { eligible: false, discount: { amount: 0, currency: context.currency }, reason: "PROMOTION_NOT_ACTIVE" }; if (context.at < promotion.startsAt || (promotion.endsAt && context.at > promotion.endsAt)) return { eligible: false, discount: { amount: 0, currency: context.currency }, reason: "PROMOTION_OUTSIDE_WINDOW" }; const eligible = await deps.eligibility.check(context, promotion); if (!eligible.eligible) return { eligible: false, discount: { amount: 0, currency: context.currency }, reason: eligible.reason ?? "NOT_ELIGIBLE" }; const result = await deps.calculation.calculate(context, promotion); deps.telemetry.metric("promotion.evaluated", 1, { tenantId: context.tenantId, promotionId: promotion.id, eligible: String(result.eligible) }); return result; }
export async function applyPromotionAction(record: Promotion, action: PromotionAction, at: ISODateTime, deps: { repository: PromotionRepository; events: PromotionEventRepository; audit: PromotionAuditPort; telemetry: PromotionTelemetryPort }): Promise<{ ok: boolean; promotion?: Promotion; errorCode?: string; message?: string }> { const next = transitionPromotionStatus(record.status, action); if (!next) return { ok: false, errorCode: "INVALID_TRANSITION", message: `Cannot apply ${action} from ${record.status}` }; const updated = await deps.repository.update({ ...record, status: next, updatedAt: at }); const event: PromotionEvent = { id: `proevt_${updated.id}_${at}_${action}`, promotionId: updated.id, action, occurredAt: at, fromStatus: record.status, toStatus: next }; await deps.events.append(event); await deps.audit.record(event); deps.telemetry.metric("promotion.transition", 1, { tenantId: updated.tenantId, status: next, action }); return { ok: true, promotion: updated }; }
