import { BillingActivationPolicy, BillingAuditPort, BillingCalculationPort, BillingPaymentPort, BillingValidationPort, BillingTelemetryPort, InvoiceIssuancePort, InvoiceRepository } from './contracts';
import { Invoice, InvoiceId } from './types';
import { validateInvoice } from './validation';
export class BillingLifecycle {
  constructor(private readonly invoices: InvoiceRepository, private readonly calculation: BillingCalculationPort, private readonly issuance: InvoiceIssuancePort, private readonly payments: BillingPaymentPort, private readonly validation: BillingValidationPort | null, private readonly activation: BillingActivationPolicy, private readonly audit: BillingAuditPort, private readonly telemetry: BillingTelemetryPort) {}
  async prepare(invoice: Invoice): Promise<Invoice> { if (!(await this.activation.isEnabled(invoice.tenantId))) throw new Error('Billing is not active'); const calculated = await this.calculation.calculate(invoice); validateInvoice(calculated); await this.validation?.validate(calculated); await this.invoices.save(calculated); await this.audit.record('INVOICE_PREPARED', calculated.id); return calculated; }
  async issue(invoice: Invoice): Promise<Invoice> { if (!(await this.activation.isEnabled(invoice.tenantId))) throw new Error('Billing is not active'); const calculated = await this.calculation.calculate(invoice); validateInvoice(calculated); await this.validation?.validate(calculated); const issued = await this.issuance.issue(calculated); await this.invoices.save(issued); await this.audit.record('INVOICE_ISSUED', issued.id); await this.telemetry.record('billing.invoice.issued', 1, { invoiceId: issued.id }); return issued; }
  async applyPayment(invoiceId: InvoiceId, amount: number, currency: string, reference?: string): Promise<Invoice> { const invoice = await this.invoices.get(invoiceId); if (!invoice) throw new Error('Invoice not found'); if (!(await this.activation.isEnabled(invoice.tenantId))) throw new Error('Billing is not active'); const updated = await this.payments.applyPayment(invoiceId, amount, currency, reference); validateInvoice(updated); await this.invoices.save(updated); await this.audit.record('INVOICE_PAYMENT_APPLIED', invoiceId); await this.telemetry.record('billing.invoice.payment_applied', amount, { invoiceId }); return updated; }
  async void(invoiceId: InvoiceId, tenantId: string | undefined, reason: string): Promise<Invoice> { if (!(await this.activation.isEnabled(tenantId))) throw new Error('Billing is not active'); if (!reason.trim()) throw new Error('Void reason is required'); const updated = await this.issuance.void(invoiceId, reason); await this.invoices.save(updated); await this.audit.record('INVOICE_VOIDED', invoiceId, { reason }); return updated; }
}