export type ID = string;
export type ISODateTime = string;
export type SubscriptionStatus = "DRAFT" | "PENDING" | "ACTIVE" | "PAUSED" | "PAST_DUE" | "CANCELLED" | "EXPIRED" | "SUSPENDED";
export type SubscriptionAction = "CREATE" | "ACTIVATE" | "PAUSE" | "RESUME" | "CHANGE_PLAN" | "CANCEL" | "RENEW" | "SUSPEND" | "EXPIRE";
export type BillingInterval = "DAY" | "WEEK" | "MONTH" | "QUARTER" | "YEAR";
export type BillingMode = "PREPAID" | "POSTPAID";
export type SubscriptionSource = "CUSTOMER" | "ADMIN" | "API" | "SYSTEM" | "PROMOTION" | "MIGRATION";
export interface Money { amount: number; currency: string; }
export interface SubscriptionPlanRef { planId: ID; version?: string; externalRef?: string; }
export interface BillingCycle { interval: BillingInterval; count: number; anchorAt: ISODateTime; nextBillingAt: ISODateTime; }
export interface SubscriptionContext { tenantId: ID; customerId: ID; orderId?: ID; invoiceId?: ID; productId?: ID; serviceId?: ID; locale?: string; region?: string; }
export interface SubscriptionRecord { id: ID; context: SubscriptionContext; plan: SubscriptionPlanRef; status: SubscriptionStatus; billingMode: BillingMode; cycle: BillingCycle; price: Money; source: SubscriptionSource; startedAt?: ISODateTime; currentPeriodStart: ISODateTime; currentPeriodEnd: ISODateTime; cancelledAt?: ISODateTime; metadata?: Record<string, string>; createdAt: ISODateTime; updatedAt: ISODateTime; }
export interface SubscriptionEvent { id: ID; subscriptionId: ID; action: SubscriptionAction; occurredAt: ISODateTime; actorId?: ID; reason?: string; fromStatus?: SubscriptionStatus; toStatus?: SubscriptionStatus; idempotencyKey?: string; }
export interface SubscriptionQuery { tenantId: ID; customerId?: ID; status?: SubscriptionStatus; planId?: ID; limit?: number; }
export interface SubscriptionResult { ok: boolean; subscription?: SubscriptionRecord; errorCode?: string; message?: string; }
export interface BillingCycleResult { ok: boolean; periodStart?: ISODateTime; periodEnd?: ISODateTime; nextBillingAt?: ISODateTime; errorCode?: string; message?: string; }
export interface SubscriptionRepository { create(record: SubscriptionRecord): Promise<SubscriptionRecord>; getById(tenantId: ID, subscriptionId: ID): Promise<SubscriptionRecord | null>; update(record: SubscriptionRecord): Promise<SubscriptionRecord>; list(query: SubscriptionQuery): Promise<SubscriptionRecord[]>; }
export interface SubscriptionEventRepository { append(event: SubscriptionEvent): Promise<void>; list(subscriptionId: ID): Promise<SubscriptionEvent[]>; }
export interface SubscriptionPlanPort { resolve(tenantId: ID, planId: ID, version?: string): Promise<SubscriptionPlanRef | null>; }
export interface SubscriptionEligibilityPort { check(record: SubscriptionRecord, action: SubscriptionAction): Promise<{ allowed: boolean; reason?: string }>; }
export interface SubscriptionBillingPort { generateCycle(subscription: SubscriptionRecord, at: ISODateTime): Promise<BillingCycleResult>; }
export interface SubscriptionPaymentPort { requestCollection(input: { tenantId: ID; customerId: ID; subscriptionId: ID; amount: Money; invoiceReference?: ID; idempotencyKey: string; }): Promise<{ accepted: boolean; paymentReference?: ID; reason?: string }>; }
export interface SubscriptionInvoicePort { prepare(input: { tenantId: ID; customerId: ID; subscriptionId: ID; periodStart: ISODateTime; periodEnd: ISODateTime; amount: Money; }): Promise<{ invoiceReference: ID }>; }
export interface SubscriptionReconciliationPort { reference(input: { tenantId: ID; subscriptionId: ID; invoiceReference?: ID; paymentReference?: ID; }): Promise<void>; }
export interface SubscriptionAuditPort { record(event: SubscriptionEvent): Promise<void>; }
export interface SubscriptionTelemetryPort { metric(name: string, value: number, dimensions?: Record<string, string>): void; }
export interface SubscriptionActivationPolicy { isEnabled(tenantId: ID): Promise<boolean>; }
export interface SubscriptionValidationPort { validate(record: SubscriptionRecord): Promise<{ valid: boolean; errors: string[] }>; }
const SECRET_PATTERNS = [/password/i, /secret/i, /private[ _-]?key/i, /access[ _-]?token/i, /refresh[ _-]?token/i, /api[ _-]?key/i, /authorization/i, /cvv|cvc/i, /pan/i, /card[ _-]?number/i];
export function containsSensitiveKey(value: string): boolean { return SECRET_PATTERNS.some((pattern) => pattern.test(value)); }
export function validateSubscriptionInput(record: SubscriptionRecord): string[] { const errors: string[] = []; if (!record.id) errors.push("subscription.id is required"); if (!record.context.tenantId) errors.push("context.tenantId is required"); if (!record.context.customerId) errors.push("context.customerId is required"); if (!record.plan.planId) errors.push("plan.planId is required"); if (!record.price.currency) errors.push("price.currency is required"); if (!Number.isFinite(record.price.amount) || record.price.amount < 0) errors.push("price.amount must be finite and non-negative"); if (!Number.isInteger(record.cycle.count) || record.cycle.count < 1) errors.push("cycle.count must be a positive integer"); if (record.metadata && Object.keys(record.metadata).some(containsSensitiveKey)) errors.push("metadata contains a sensitive key"); return errors; }
export function transitionStatus(current: SubscriptionStatus, action: SubscriptionAction): SubscriptionStatus | null { const map: Record<SubscriptionStatus, Partial<Record<SubscriptionAction, SubscriptionStatus>>> = { DRAFT: { CREATE: "PENDING", ACTIVATE: "ACTIVE", CANCEL: "CANCELLED" }, PENDING: { ACTIVATE: "ACTIVE", CANCEL: "CANCELLED", SUSPEND: "SUSPENDED" }, ACTIVE: { PAUSE: "PAUSED", CHANGE_PLAN: "ACTIVE", CANCEL: "CANCELLED", RENEW: "ACTIVE", SUSPEND: "SUSPENDED", EXPIRE: "EXPIRED" }, PAUSED: { RESUME: "ACTIVE", CANCEL: "CANCELLED", SUSPEND: "SUSPENDED" }, PAST_DUE: { RENEW: "ACTIVE", CANCEL: "CANCELLED", SUSPEND: "SUSPENDED" }, CANCELLED: {}, EXPIRED: { ACTIVATE: "ACTIVE" }, SUSPENDED: { RESUME: "ACTIVE", CANCEL: "CANCELLED" } }; return map[current][action] ?? null; }
export async function createSubscription(record: SubscriptionRecord, deps: { activation: SubscriptionActivationPolicy; validation: SubscriptionValidationPort; repository: SubscriptionRepository; events: SubscriptionEventRepository; audit: SubscriptionAuditPort; telemetry: SubscriptionTelemetryPort }): Promise<SubscriptionResult> { if (!(await deps.activation.isEnabled(record.context.tenantId))) return { ok: false, errorCode: "FEATURE_DISABLED", message: "Subscription activation is disabled" }; const errors = await deps.validation.validate(record); if (!errors.valid) return { ok: false, errorCode: "VALIDATION_FAILED", message: errors.errors.join("; ") }; const created = await deps.repository.create(record); const event: SubscriptionEvent = { id: `subevt_${created.id}_${created.createdAt}`, subscriptionId: created.id, action: "CREATE", occurredAt: created.createdAt, toStatus: created.status }; await deps.events.append(event); await deps.audit.record(event); deps.telemetry.metric("subscription.created", 1, { tenantId: created.context.tenantId }); return { ok: true, subscription: created }; }
export async function applySubscriptionAction(record: SubscriptionRecord, action: SubscriptionAction, at: ISODateTime, deps: { eligibility: SubscriptionEligibilityPort; repository: SubscriptionRepository; events: SubscriptionEventRepository; audit: SubscriptionAuditPort; telemetry: SubscriptionTelemetryPort }): Promise<SubscriptionResult> { const next = transitionStatus(record.status, action); if (!next) return { ok: false, errorCode: "INVALID_TRANSITION", message: `Cannot apply ${action} from ${record.status}` }; const eligibility = await deps.eligibility.check(record, action); if (!eligibility.allowed) return { ok: false, errorCode: "NOT_ELIGIBLE", message: eligibility.reason ?? "Action is not eligible" }; const updated = await deps.repository.update({ ...record, status: next, updatedAt: at, ...(action === "CANCEL" ? { cancelledAt: at } : {}) }); const event: SubscriptionEvent = { id: `subevt_${updated.id}_${at}_${action}`, subscriptionId: updated.id, action, occurredAt: at, fromStatus: record.status, toStatus: next }; await deps.events.append(event); await deps.audit.record(event); deps.telemetry.metric("subscription.transition", 1, { status: next, action }); return { ok: true, subscription: updated }; }
