export type ID = string;
export type ISODateTime = string;
export type MeterStatus = "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
export type EntitlementStatus = "PENDING" | "ACTIVE" | "EXHAUSTED" | "EXPIRED" | "SUSPENDED" | "REVOKED";
export type UsageSource = "CUSTOMER" | "SYSTEM" | "API" | "ADMIN" | "DEVICE" | "INTEGRATION";
export type UsageAction = "RECORD" | "ADJUST" | "FINALIZE" | "VOID";
export type EntitlementAction = "GRANT" | "ACTIVATE" | "SUSPEND" | "RESUME" | "REVOKE" | "EXPIRE";
export type MeterAggregation = "SUM" | "COUNT" | "MAX" | "MIN" | "LAST";
export type EntitlementUnit = "UNIT" | "REQUEST" | "MINUTE" | "HOUR" | "GB" | "ITEM" | "CUSTOM";
export interface MeterDefinition { id: ID; tenantId: ID; code: string; name: string; unit: EntitlementUnit; aggregation: MeterAggregation; active: boolean; createdAt: ISODateTime; updatedAt: ISODateTime; }
export interface UsageRecord { id: ID; tenantId: ID; customerId?: ID; subscriptionId?: ID; meterId: ID; quantity: number; occurredAt: ISODateTime; source: UsageSource; referenceId?: ID; idempotencyKey?: string; metadata?: Record<string, string>; }
export interface UsageSummary { tenantId: ID; meterId: ID; customerId?: ID; subscriptionId?: ID; periodStart: ISODateTime; periodEnd: ISODateTime; quantity: number; aggregation: MeterAggregation; }
export interface EntitlementLimit { meterId: ID; includedQuantity?: number; maximumQuantity?: number; unit: EntitlementUnit; }
export interface EntitlementRecord { id: ID; tenantId: ID; customerId: ID; subscriptionId?: ID; planId?: ID; status: EntitlementStatus; limits: EntitlementLimit[]; effectiveFrom: ISODateTime; effectiveTo?: ISODateTime; createdAt: ISODateTime; updatedAt: ISODateTime; }
export interface UsageEvent { id: ID; usageId: ID; action: UsageAction; occurredAt: ISODateTime; actorId?: ID; reason?: string; }
export interface EntitlementEvent { id: ID; entitlementId: ID; action: EntitlementAction; occurredAt: ISODateTime; actorId?: ID; reason?: string; fromStatus?: EntitlementStatus; toStatus?: EntitlementStatus; }
export interface UsageRepository { append(record: UsageRecord): Promise<UsageRecord>; getById(tenantId: ID, usageId: ID): Promise<UsageRecord | null>; list(query: { tenantId: ID; meterId?: ID; customerId?: ID; subscriptionId?: ID; from?: ISODateTime; to?: ISODateTime; limit?: number }): Promise<UsageRecord[]>; }
export interface MeterRepository { create(meter: MeterDefinition): Promise<MeterDefinition>; getById(tenantId: ID, meterId: ID): Promise<MeterDefinition | null>; update(meter: MeterDefinition): Promise<MeterDefinition>; }
export interface EntitlementRepository { create(record: EntitlementRecord): Promise<EntitlementRecord>; getById(tenantId: ID, entitlementId: ID): Promise<EntitlementRecord | null>; update(record: EntitlementRecord): Promise<EntitlementRecord>; list(query: { tenantId: ID; customerId?: ID; subscriptionId?: ID; status?: EntitlementStatus }): Promise<EntitlementRecord[]>; }
export interface UsageAggregationPort { summarize(input: { tenantId: ID; meterId: ID; customerId?: ID; subscriptionId?: ID; from: ISODateTime; to: ISODateTime }): Promise<UsageSummary>; }
export interface EntitlementEvaluationPort { evaluate(input: { entitlement: EntitlementRecord; meterId: ID; requestedQuantity: number; at: ISODateTime }): Promise<{ allowed: boolean; remaining?: number; reason?: string }>; }
export interface UsageValidationPort { validate(record: UsageRecord): Promise<{ valid: boolean; errors: string[] }>; }
export interface EntitlementValidationPort { validate(record: EntitlementRecord): Promise<{ valid: boolean; errors: string[] }>; }
export interface UsageEligibilityPort { check(record: UsageRecord): Promise<{ allowed: boolean; reason?: string }>; }
export interface UsageAuditPort { record(event: UsageEvent | EntitlementEvent): Promise<void>; }
export interface UsageTelemetryPort { metric(name: string, value: number, dimensions?: Record<string, string>): void; }
export interface UsageActivationPolicy { isEnabled(tenantId: ID): Promise<boolean>; }
export interface UsageEventRepository { append(event: UsageEvent): Promise<void>; }
export interface EntitlementEventRepository { append(event: EntitlementEvent): Promise<void>; }
const SECRET_PATTERNS = [/password/i, /secret/i, /private[ _-]?key/i, /access[ _-]?token/i, /refresh[ _-]?token/i, /api[ _-]?key/i, /authorization/i, /cvv|cvc/i, /pan/i, /card[ _-]?number/i];
export function containsSensitiveKey(value: string): boolean { return SECRET_PATTERNS.some((pattern) => pattern.test(value)); }
export function validateUsageInput(record: UsageRecord): string[] { const errors: string[] = []; if (!record.id) errors.push("usage.id is required"); if (!record.tenantId) errors.push("usage.tenantId is required"); if (!record.meterId) errors.push("usage.meterId is required"); if (!Number.isFinite(record.quantity) || record.quantity < 0) errors.push("usage.quantity must be finite and non-negative"); if (record.metadata && Object.keys(record.metadata).some(containsSensitiveKey)) errors.push("metadata contains a sensitive key"); return errors; }
export function validateEntitlementInput(record: EntitlementRecord): string[] { const errors: string[] = []; if (!record.id) errors.push("entitlement.id is required"); if (!record.tenantId) errors.push("entitlement.tenantId is required"); if (!record.customerId) errors.push("entitlement.customerId is required"); if (!record.limits.length) errors.push("entitlement.limits must not be empty"); for (const limit of record.limits) { if (limit.includedQuantity !== undefined && (!Number.isFinite(limit.includedQuantity) || limit.includedQuantity < 0)) errors.push(`invalid includedQuantity for ${limit.meterId}`); if (limit.maximumQuantity !== undefined && (!Number.isFinite(limit.maximumQuantity) || limit.maximumQuantity < 0)) errors.push(`invalid maximumQuantity for ${limit.meterId}`); if (limit.includedQuantity !== undefined && limit.maximumQuantity !== undefined && limit.maximumQuantity < limit.includedQuantity) errors.push(`maximumQuantity below includedQuantity for ${limit.meterId}`); } return errors; }
export function transitionEntitlementStatus(current: EntitlementStatus, action: EntitlementAction): EntitlementStatus | null { const map: Record<EntitlementStatus, Partial<Record<EntitlementAction, EntitlementStatus>>> = { PENDING: { GRANT: "ACTIVE", ACTIVATE: "ACTIVE", REVOKE: "REVOKED", EXPIRE: "EXPIRED" }, ACTIVE: { SUSPEND: "SUSPENDED", REVOKE: "REVOKED", EXPIRE: "EXPIRED" }, EXHAUSTED: { ACTIVATE: "ACTIVE", SUSPEND: "SUSPENDED", REVOKE: "REVOKED", EXPIRE: "EXPIRED" }, EXPIRED: {}, SUSPENDED: { RESUME: "ACTIVE", REVOKE: "REVOKED", EXPIRE: "EXPIRED" }, REVOKED: {} }; return map[current][action] ?? null; }
export async function recordUsage(record: UsageRecord, deps: { activation: UsageActivationPolicy; validation: UsageValidationPort; eligibility: UsageEligibilityPort; repository: UsageRepository; events: UsageEventRepository; audit: UsageAuditPort; telemetry: UsageTelemetryPort }): Promise<{ ok: boolean; usage?: UsageRecord; errorCode?: string; message?: string }> { if (!(await deps.activation.isEnabled(record.tenantId))) return { ok: false, errorCode: "FEATURE_DISABLED", message: "Usage activation is disabled" }; const errors = await deps.validation.validate(record); if (!errors.valid) return { ok: false, errorCode: "VALIDATION_FAILED", message: errors.errors.join("; ") }; const eligible = await deps.eligibility.check(record); if (!eligible.allowed) return { ok: false, errorCode: "NOT_ELIGIBLE", message: eligible.reason ?? "Usage is not eligible" }; const created = await deps.repository.append(record); const event: UsageEvent = { id: `usageevt_${created.id}_${created.occurredAt}`, usageId: created.id, action: "RECORD", occurredAt: created.occurredAt }; await deps.events.append(event); await deps.audit.record(event); deps.telemetry.metric("usage.recorded", created.quantity, { tenantId: created.tenantId, meterId: created.meterId }); return { ok: true, usage: created }; }
export async function applyEntitlementAction(record: EntitlementRecord, action: EntitlementAction, at: ISODateTime, deps: { repository: EntitlementRepository; events: EntitlementEventRepository; audit: UsageAuditPort; telemetry: UsageTelemetryPort }): Promise<{ ok: boolean; entitlement?: EntitlementRecord; errorCode?: string; message?: string }> { const next = transitionEntitlementStatus(record.status, action); if (!next) return { ok: false, errorCode: "INVALID_TRANSITION", message: `Cannot apply ${action} from ${record.status}` }; const updated = await deps.repository.update({ ...record, status: next, updatedAt: at }); const event: EntitlementEvent = { id: `entevt_${updated.id}_${at}_${action}`, entitlementId: updated.id, action, occurredAt: at, fromStatus: record.status, toStatus: next }; await deps.events.append(event); await deps.audit.record(event); deps.telemetry.metric("entitlement.transition", 1, { tenantId: updated.tenantId, status: next, action }); return { ok: true, entitlement: updated }; }
