export type GatewayStatus = 'PLANNED'|'ACTIVE'|'PAUSED'|'DEPRECATED';
export type RouteStatus = 'DRAFT'|'ACTIVE'|'PAUSED'|'DEPRECATED';
export type GatewayProtocol = 'HTTP'|'HTTPS'|'WEBSOCKET'|'CUSTOM';
export type PolicyKind = 'CORS'|'RATE_LIMIT'|'REQUEST_SIZE'|'TIMEOUT'|'IP_FILTER'|'HEADER'|'METHOD'|'VERSION'|'CUSTOM';
export type HealthStatus = 'UNKNOWN'|'HEALTHY'|'DEGRADED'|'UNAVAILABLE';
export type GatewayErrorCode = 'INVALID_REQUEST'|'ROUTE_NOT_FOUND'|'METHOD_NOT_ALLOWED'|'RATE_LIMITED'|'REQUEST_TOO_LARGE'|'TIMEOUT'|'POLICY_BLOCKED'|'UPSTREAM_UNAVAILABLE'|'INTERNAL_ERROR';
export interface GatewayContext { requestId:string; correlationId:string; tenantId?:string; clientId?:string; timestamp:string; metadata?:Record<string,unknown>; }
export interface RouteDefinition { id:string; name:string; version:string; path:string; methods:string[]; target:string; status:RouteStatus; authRequired:boolean; policies:PolicyKind[]; }
export interface GatewayPolicy { id:string; kind:PolicyKind; enabled:boolean; configuration:Record<string,unknown>; }
export interface GatewayRequest { context:GatewayContext; protocol:GatewayProtocol; method:string; path:string; headers:Record<string,string>; query:Record<string,string>; body?:unknown; }
export interface GatewayResponse { status:number; headers:Record<string,string>; body?:unknown; requestId:string; correlationId:string; }
export interface GatewayError { code:GatewayErrorCode; message:string; status:number; requestId:string; correlationId:string; }
export interface GatewayHealth { status:HealthStatus; checkedAt:string; latencyMs?:number; details?:Record<string,string>; }
export interface GatewayDecision { allowed:boolean; routeId?:string; reason?:string; }
export interface GatewayAuditPort { record(event:Record<string,unknown>):Promise<void>; }
export interface GatewayTelemetryPort { metric(name:string,value:number,dimensions?:Record<string,string>):Promise<void>; }
export interface GatewayRoutePort { resolve(request:GatewayRequest):Promise<RouteDefinition|undefined>; }
export interface GatewayPolicyPort { evaluate(request:GatewayRequest,route:RouteDefinition):Promise<GatewayDecision>; }
export interface GatewayAuthenticationPort { authenticate(request:GatewayRequest):Promise<{authenticated:boolean; principalId?:string}>; }
export interface GatewayAuthorizationPort { authorize(request:GatewayRequest,route:RouteDefinition,principalId?:string):Promise<GatewayDecision>; }
export interface GatewayUpstreamPort { dispatch(request:GatewayRequest,route:RouteDefinition):Promise<GatewayResponse>; }
const SENSITIVE=/(password|secret|private.?key|access.?token|refresh.?token|api.?key|authorization|bearer|cvv|cvc|pan|card.?number)/i;
export function validateMetadata(metadata:Record<string,unknown>|undefined):void { if(!metadata)return; for(const key of Object.keys(metadata)) if(SENSITIVE.test(key)) throw new Error(`Sensitive metadata key rejected: ${key}`); }
export function validateRequest(request:GatewayRequest):void { if(!request.context.requestId||!request.context.correlationId) throw new Error('requestId and correlationId are required'); if(!request.method||!request.path) throw new Error('method and path are required'); validateMetadata(request.context.metadata); }
export function normalizeError(error:unknown,context:GatewayContext):GatewayError { return {code:'INTERNAL_ERROR',message:error instanceof Error?error.message:'Gateway error',status:500,requestId:context.requestId,correlationId:context.correlationId}; }
export async function handleGatewayRequest(request:GatewayRequest,deps:{routes:GatewayRoutePort; policies:GatewayPolicyPort; auth:GatewayAuthenticationPort; authorization:GatewayAuthorizationPort; upstream:GatewayUpstreamPort; audit?:GatewayAuditPort; telemetry?:GatewayTelemetryPort}):Promise<GatewayResponse>{ validateRequest(request); const route=await deps.routes.resolve(request); if(!route)return {status:404,headers:{'content-type':'application/json'},body:{code:'ROUTE_NOT_FOUND'},requestId:request.context.requestId,correlationId:request.context.correlationId}; const policy=await deps.policies.evaluate(request,route); if(!policy.allowed)return {status:403,headers:{'content-type':'application/json'},body:{code:'POLICY_BLOCKED',reason:policy.reason},requestId:request.context.requestId,correlationId:request.context.correlationId}; let principalId:string|undefined; if(route.authRequired){const auth=await deps.auth.authenticate(request); if(!auth.authenticated)return {status:401,headers:{'content-type':'application/json'},body:{code:'UNAUTHORIZED'},requestId:request.context.requestId,correlationId:request.context.correlationId}; principalId=auth.principalId;} const access=await deps.authorization.authorize(request,route,principalId); if(!access.allowed)return {status:403,headers:{'content-type':'application/json'},body:{code:'FORBIDDEN',reason:access.reason},requestId:request.context.requestId,correlationId:request.context.correlationId}; const response=await deps.upstream.dispatch(request,route); await deps.audit?.record({type:'gateway.request',requestId:request.context.requestId,correlationId:request.context.correlationId,routeId:route.id,status:response.status}); await deps.telemetry?.metric('gateway.requests',1,{routeId:route.id}); return response; }
export const STEP_71={name:'API Gateway & Edge Delivery Foundation',version:'1.0.0',status:'FOUNDATION',flow:'Client → Edge/Gateway → Route Resolution → Policy Enforcement → Authentication/Authorization → Upstream Delivery → Normalized Response → Audit/Telemetry',ownership:['gateway boundary','route resolution and versioning','edge policy contracts','request limits and timeout boundaries','CORS/header/method policy boundaries','authentication/authorization delegation','upstream delivery boundary','gateway health and telemetry hooks'],exclusions:['business logic','domain ownership','application use-case ownership','customer identity source of truth','payment/accounting source of truth','analytics source of truth','audit source of truth','provider credentials/secrets'],providerNeutral:true};
