/** D1-backed domain repositories for the operational foundation. */
import type { Cart, CartRepositoryPortV1, CustomerId, CustomerProfile, CustomerRepositoryPortV1, Order, OrderId, OrderRepositoryPortV1, PartnerAccount, PartnerId, PartnerRepositoryPortV1, Product, ProductId, ProductRepositoryPortV1, Service, ServiceId, ServiceRepositoryPortV1 } from "../../../domains/src/index.js";
import type { D1DatabaseLike } from "../d1.js";
async function one<T>(db:D1DatabaseLike,sql:string,values:readonly unknown[]):Promise<T|null>{const statement=db.prepare(sql);const bound=values.length?statement.bind(...values):statement;const result=await bound.all<T&Record<string,unknown>>();return (result.results[0] as T|undefined)??null;}
export class D1CustomerRepository implements CustomerRepositoryPortV1{constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string){}async findById(id:CustomerId){return one<CustomerProfile>(this.db,"SELECT id,status,display_name AS displayName,locale,timezone FROM customers WHERE id=? AND tenant_id=?",[id,this.tenantId]);}async save(entity:CustomerProfile){const row=await one<CustomerProfile>(this.db,"INSERT INTO customers (id,tenant_id,display_name,status,locale,timezone) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET display_name=excluded.display_name,status=excluded.status,locale=excluded.locale,timezone=excluded.timezone,updated_at=CURRENT_TIMESTAMP WHERE customers.tenant_id=excluded.tenant_id RETURNING id,status,display_name AS displayName,locale,timezone",[entity.id,this.tenantId,entity.displayName,entity.status,entity.locale??null,entity.timezone??null]);if(!row)throw new Error("Customer persistence returned no row");return row;}}
export class D1ProductRepository implements ProductRepositoryPortV1{constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string){}async findById(id:ProductId){return one<Product>(this.db,"SELECT id,owner_id AS ownerId,catalog_id AS catalogId,name,status FROM products WHERE id=? AND tenant_id=?",[id,this.tenantId]);}async save(entity:Product){const row=await one<Product>(this.db,"INSERT INTO products (id,tenant_id,owner_id,catalog_id,name,status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET owner_id=excluded.owner_id,catalog_id=excluded.catalog_id,name=excluded.name,status=excluded.status,updated_at=CURRENT_TIMESTAMP WHERE products.tenant_id=excluded.tenant_id RETURNING id,owner_id AS ownerId,catalog_id AS catalogId,name,status",[entity.id,this.tenantId,entity.ownerId,entity.catalogId??null,entity.name,entity.status]);if(!row)throw new Error("Product persistence returned no row");return row;}}
export class D1ServiceRepository implements ServiceRepositoryPortV1{constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string){}async findById(id:ServiceId){return one<Service>(this.db,"SELECT id,owner_id AS ownerId,catalog_id AS catalogId,name,status FROM services WHERE id=? AND tenant_id=?",[id,this.tenantId]);}async save(entity:Service){const row=await one<Service>(this.db,"INSERT INTO services (id,tenant_id,owner_id,catalog_id,name,status) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET owner_id=excluded.owner_id,catalog_id=excluded.catalog_id,name=excluded.name,status=excluded.status,updated_at=CURRENT_TIMESTAMP WHERE services.tenant_id=excluded.tenant_id RETURNING id,owner_id AS ownerId,catalog_id AS catalogId,name,status",[entity.id,this.tenantId,entity.ownerId,entity.catalogId??null,entity.name,entity.status]);if(!row)throw new Error("Service persistence returned no row");return row;}}
export class D1PartnerRepository implements PartnerRepositoryPortV1{constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string){}async findById(id:PartnerId){return one<PartnerAccount>(this.db,"SELECT id,legal_name AS legalName,status,tenant_id AS tenantId FROM partners WHERE id=? AND tenant_id=?",[id,this.tenantId]);}async save(entity:PartnerAccount){if(entity.tenantId!==this.tenantId)throw new Error("Partner tenant mismatch");const row=await one<PartnerAccount>(this.db,"INSERT INTO partners (id,tenant_id,legal_name,status) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET legal_name=excluded.legal_name,status=excluded.status,updated_at=CURRENT_TIMESTAMP WHERE partners.tenant_id=excluded.tenant_id RETURNING id,legal_name AS legalName,status,tenant_id AS tenantId",[entity.id,this.tenantId,entity.legalName,entity.status]);if(!row)throw new Error("Partner persistence returned no row");return row;}async verify(id:PartnerId){const row=await one<PartnerAccount>(this.db,"UPDATE partners SET status='VERIFIED',updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND status='PENDING' RETURNING id,legal_name AS legalName,status,tenant_id AS tenantId",[id,this.tenantId]);if(row)return row;const existing=await this.findById(id);if(!existing)throw new Error("Partner not found");if(existing.status!=="VERIFIED")throw new Error(`Partner cannot be verified from status ${existing.status}`);return existing;}}
export class D1CartRepository implements CartRepositoryPortV1{constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string,private readonly currency:string){}async findById(id:string){return one<Cart>(this.db,"SELECT id,customer_id AS customerId,status FROM carts WHERE id=? AND tenant_id=?",[id,this.tenantId]);}async save(entity:Cart){const customer=await one<{id:string}>(this.db,"SELECT id FROM customers WHERE id=? AND tenant_id=? AND status IN ('PROSPECT','ACTIVE')",[entity.customerId,this.tenantId]);if(!customer)throw new Error("Customer not found for tenant");const row=await one<Cart>(this.db,"INSERT INTO carts (id,tenant_id,customer_id,status,currency) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET customer_id=excluded.customer_id,status=excluded.status,updated_at=CURRENT_TIMESTAMP WHERE carts.tenant_id=excluded.tenant_id RETURNING id,customer_id AS customerId,status",[entity.id,this.tenantId,entity.customerId,entity.status,this.currency]);if(!row)throw new Error("Cart persistence returned no row");return row;}}
export class D1OrderRepository implements OrderRepositoryPortV1{
  constructor(private readonly db:D1DatabaseLike,private readonly tenantId:string){}
  async findById(id:OrderId){
    const row=await one<Record<string,unknown>>(this.db,"SELECT id,customer_id,status,total_amount,currency FROM orders WHERE id=? AND tenant_id=?",[id,this.tenantId]);
    return row?{id:row.id as OrderId,customerId:String(row.customer_id),status:row.status as Order["status"],total:{amount:Number(row.total_amount),currency:String(row.currency)}}:null;
  }
  async save(entity:Order){
    const row=await one<Record<string,unknown>>(this.db,"INSERT INTO orders (id,tenant_id,customer_id,status,total_amount,currency) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET customer_id=excluded.customer_id,status=excluded.status,total_amount=excluded.total_amount,currency=excluded.currency,updated_at=CURRENT_TIMESTAMP WHERE orders.tenant_id=excluded.tenant_id RETURNING id,customer_id,status,total_amount,currency",[entity.id,this.tenantId,entity.customerId,entity.status,entity.total.amount,entity.total.currency]);
    if(!row)throw new Error("Order persistence returned no row");
    return{id:row.id as OrderId,customerId:String(row.customer_id),status:row.status as Order["status"],total:{amount:Number(row.total_amount),currency:String(row.currency)}};
  }
  async updateStatus(id:OrderId,status:Order["status"],correlationId:string){
    const existing=await this.findById(id);
    if(!existing)throw new Error("Order not found for tenant");
    const row=await one<Record<string,unknown>>(this.db,"UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? RETURNING id,customer_id,status,total_amount,currency",[status,id,this.tenantId]);
    if(!row)throw new Error("Order status update returned no row");
    const updated={id:row.id as OrderId,customerId:String(row.customer_id),status:row.status as Order["status"],total:{amount:Number(row.total_amount),currency:String(row.currency)}};
    const eventId=crypto.randomUUID();
    await this.db.prepare("INSERT INTO order_events (id,tenant_id,order_id,from_status,to_status,correlation_id) VALUES (?,?,?,?,?,?)").bind(eventId,this.tenantId,id,existing.status,status,correlationId).all();
    return updated;
  }
}
export const D1_DOMAIN_REPOSITORIES_VERSION="1.5.0" as const;
