import type { PayoutApprovalPort, PayoutAuditPort, PayoutEligibilityPort, PayoutPort, PayoutRepository, PayoutReversalPort, PayoutTelemetryPort, PayoutValidationPort, PayoutActivationPolicy } from './contracts';
import type { PayoutContext, PayoutInstruction, PayoutRecord, PayoutResult } from './types';
import { validateInstruction, validatePayout } from './validation';
export class PayoutLifecycle implements PayoutPort {
 constructor(private readonly repo:PayoutRepository, private readonly eligibility:PayoutEligibilityPort, private readonly approval:PayoutApprovalPort, private readonly reversal:PayoutReversalPort, private readonly validation:PayoutValidationPort=validatePayoutAdapter(), private readonly audit?:PayoutAuditPort, private readonly telemetry?:PayoutTelemetryPort, private readonly activation?:PayoutActivationPolicy) {}
 async create(p:PayoutRecord):Promise<PayoutResult>{ await this.ensure(p.context); this.validation.validate(p); const e=await this.eligibility.check(p); if(!e.eligible) return {payout:{...p,status:'ON_HOLD',failureReason:e.reason,updatedAt:new Date().toISOString()},accepted:false,message:e.reason}; await this.repo.save(p); await this.audit?.record('CREATE',p,p.context); return {payout:p,accepted:true}; }
 async approve(id:string,context?:PayoutContext):Promise<PayoutResult>{ const p=await this.repo.getById(id as PayoutRecord['id']); if(!p) return {payout:undefined as never,accepted:false,message:'Payout not found'}; await this.ensure(context||p.context); const next=await this.approval.approve(p,context); validatePayout(next); await this.repo.save(next); await this.audit?.record('APPROVE',next,context); return {payout:next,accepted:true}; }
 async process(id:string,instruction:PayoutInstruction):Promise<PayoutResult>{ const p=await this.repo.getById(id as PayoutRecord['id']); if(!p) return {payout:undefined as never,accepted:false,message:'Payout not found'}; await this.ensure(p.context); this.validation.validateInstruction(instruction); if(p.status!=='APPROVED') return {payout:p,accepted:false,message:'Payout must be APPROVED before processing'}; const next={...p,status:'PROCESSING' as const,updatedAt:new Date().toISOString()}; await this.repo.save(next); await this.audit?.record('PROCESS',next,p.context); await this.telemetry?.record('PAYOUT_PROCESSING',next,p.context); return {payout:next,accepted:true}; }
 async reverse(p:PayoutRecord,reason:string,context?:PayoutContext):Promise<PayoutRecord>{ await this.ensure(context||p.context); if(!reason.trim()) throw new Error('Reversal reason is required'); const next=await this.reversal.reverse(p,reason,context); validatePayout(next); await this.repo.save(next); await this.audit?.record('REVERSE',next,context); return next; }
 private async ensure(c?:PayoutContext){ if(this.activation && !(await this.activation.isEnabled(c))) throw new Error('Payout activation is disabled'); }
}
function validatePayoutAdapter():PayoutValidationPort{return {validate:validatePayout,validateInstruction};}