export type { EntityRecord, EntityRepository } from "./repositories.js";
export { REPOSITORY_PORT_VERSION } from "./repositories.js";
export type { CustomerId, CustomerStatus, CustomerProfile, CustomerRepositoryPort, CustomerCapabilityContract } from "./customer.js";
export { CUSTOMER_DOMAIN_VERSION } from "./customer.js";
export type { ProductId, ServiceId, CatalogId, CatalogOwnerId, Product, Service, Catalog, CatalogRepositoryPort } from "./catalog.js";
export type { CatalogCategoryKind, CatalogCategoryStatus, CatalogCategoryId, CatalogCategory, CatalogCategoryRepositoryPort } from "./catalog-taxonomy.js";
export { CATALOG_TAXONOMY_VERSION } from "./catalog-taxonomy.js";
export { CATALOG_DOMAIN_VERSION } from "./catalog.js";
export type { SolutionId, SolutionStatus, Solution, SolutionRepositoryPortV1 } from "./solution.js";
export { SOLUTION_DOMAIN_VERSION } from "./solution.js";
export type { CommercialInquiryId, CommercialInquiryStatus, CommercialInquiry, CommercialInquiryRepositoryPortV1 } from "./commercial-inquiry.js";
export { COMMERCIAL_INQUIRY_DOMAIN_VERSION } from "./commercial-inquiry.js";
export type { PartnerId, PartnerOfferId, SettlementId, PartnerAccount, PartnerStore, PartnerProduct, PartnerService, PartnerOffer, PartnerSettlement, PartnerAccessPolicy, PartnerRepositoryPort } from "./partner.js";
export { PARTNER_ECOSYSTEM_DOMAIN_VERSION } from "./partner.js";
export type { OrderId, CartId, PaymentId, OfferId, DiscountId, Money, PriceQuote, Offer, Discount, Cart, Order, PaymentTransaction, Fulfillment, Settlement, PricingPort, PromotionPort, CommerceRepositoryPort, FulfillmentPort, SettlementPort } from "./commerce.js";
export { COMMERCE_DOMAIN_VERSION } from "./commerce.js";
export { ORDER_LIFECYCLE_VERSION, ORDER_LIFECYCLE, assertOrderStatusTransition } from "./order-lifecycle.js";
export type { PaymentIntent, PaymentProviderPort, BillingPort } from "./payments.js";
export { PAYMENTS_DOMAIN_VERSION } from "./payments.js";
export type { PaymentIntentRecord, RevenueEntry, PaymentUseCaseId, PaymentIntentStatus } from "./payments-foundation.js";
export { PAYMENTS_FOUNDATION_VERSION, PAYMENT_USE_CASE_IDS, assertPaymentAmountMatchesOrder, assertPaymentTransition, PAYMENT_LIFECYCLE } from "./payments-foundation.js";
export type { InvoiceRecord, SettlementRecord, BillingUseCaseId, InvoiceStatus, SettlementStatus } from "./billing-foundation.js";
export { BILLING_FOUNDATION_VERSION, BILLING_USE_CASE_IDS, assertInvoiceAmountMatchesPayment, assertSettlementAmounts, assertSettlementOrderOwnership, BILLING_LIFECYCLE } from "./billing-foundation.js";
export type { FulfillmentRecord, FulfillmentUseCaseId, FulfillmentStatus } from "./fulfillment-foundation.js";
export { FULFILLMENT_FOUNDATION_VERSION, FULFILLMENT_USE_CASE_IDS, assertFulfillmentOrder, assertFulfillmentTransition, FULFILLMENT_LIFECYCLE } from "./fulfillment-foundation.js";
export type { ReturnRequestRecord, RefundRequestRecord, ReturnStatus, RefundRequestStatus } from "./returns-refunds-foundation.js";
export { RETURNS_REFUNDS_FOUNDATION_VERSION, RETURNS_REFUNDS_USE_CASE_IDS, assertReturnTransition, assertRefundRequestTransition, assertRefundAmount, RETURNS_REFUNDS_LIFECYCLE } from "./returns-refunds-foundation.js";
export type { RecommendationId, AgentRunId, Recommendation, SalesAssistantRequest, SalesAssistantResponse, AgentRun, RecommendationPort, SalesAssistantPort, AgentPort, ModelRouterPort } from "./ai.js";
export { AI_DOMAIN_VERSION } from "./ai.js";
export type { EntityId, MoneyValue, PercentageValue, TenantScope, ResourceScope } from "./value-objects.js";
export { money, percentage, DOMAIN_VALUE_OBJECTS_VERSION } from "./value-objects.js";
export type { CustomerRepositoryPortV1, ProductRepositoryPortV1, ServiceRepositoryPortV1, PartnerRepositoryPortV1, PartnerCatalogRepositoryPortV1, PartnerOfferRepositoryPortV1, CartRepositoryPortV1, OrderRepositoryPortV1, UnitOfWorkPort } from "./ports.js";
export { DOMAIN_REPOSITORY_PORTS_VERSION } from "./ports.js";
export type { CommerceUseCaseId } from "./commerce-foundation.js";
export { COMMERCE_FOUNDATION_VERSION, COMMERCE_USE_CASE_IDS, assertMoney, assertSameCurrency, assertOrderTotal, assertPaymentMatchesOrder, assertCheckoutableCart, assertFulfillmentAllowed, COMMERCE_LIFECYCLE } from "./commerce-foundation.js";
export type { PricingQuote, PromotionValidation } from "./pricing-promotions-foundation.js";
export { PRICING_PROMOTIONS_FOUNDATION_VERSION, assertPricingInvariant } from "./pricing-promotions-foundation.js";
export type { PricingRequestId, PricingRequestStatus, PricingRequest, PricingRequestRepositoryPortV1 } from "./pricing-request.js";
export { PRICING_REQUEST_DOMAIN_VERSION } from "./pricing-request.js";
export type { PricingDecision, PricingDecisionId, PricingDecisionStatus, PricingDecisionInput, PricingDecisionRepositoryPortV1, PricingInputDirection } from "./pricing-decision.js";
export { GOVERNED_PRICING_DOMAIN_VERSION } from "./pricing-decision.js";
export const DOMAIN_LAYER_VERSION = "2.2.0" as const;
