/** C6 post-order returns and provider-neutral refund request boundaries. */
import type { Money, OrderId, PaymentId } from "./commerce.js";

export const RETURNS_REFUNDS_FOUNDATION_VERSION = "1.0.0" as const;
export const RETURNS_REFUNDS_USE_CASE_IDS = { returnCreate: "return.create", returnProgress: "return.progress", refundRequestCreate: "refund.request.create", refundRequestProgress: "refund.request.progress" } as const;
export type ReturnStatus = "REQUESTED" | "APPROVED" | "RECEIVED" | "COMPLETED" | "CANCELLED";
export type RefundRequestStatus = "REQUESTED" | "APPROVED" | "PROCESSING" | "COMPLETED" | "FAILED" | "CANCELLED";
export interface ReturnRequestRecord { readonly id: string; readonly orderId: OrderId; readonly customerId: string; readonly status: ReturnStatus; readonly reason: string; readonly reference: string; }
export interface RefundRequestRecord { readonly id: string; readonly orderId: OrderId; readonly paymentId: PaymentId; readonly amount: Money; readonly status: RefundRequestStatus; readonly reason: string; readonly reference: string; }
export function assertReturnTransition(from: ReturnStatus, to: ReturnStatus): void { const allowed: Record<ReturnStatus, readonly ReturnStatus[]> = { REQUESTED: ["APPROVED", "CANCELLED"], APPROVED: ["RECEIVED", "CANCELLED"], RECEIVED: ["COMPLETED", "CANCELLED"], COMPLETED: [], CANCELLED: [] }; if (!allowed[from].includes(to)) throw new Error(`invalid return transition: ${from} -> ${to}`); }
export function assertRefundRequestTransition(from: RefundRequestStatus, to: RefundRequestStatus): void { const allowed: Record<RefundRequestStatus, readonly RefundRequestStatus[]> = { REQUESTED: ["APPROVED", "CANCELLED"], APPROVED: ["PROCESSING", "CANCELLED"], PROCESSING: ["COMPLETED", "FAILED"], COMPLETED: [], FAILED: [], CANCELLED: [] }; if (!allowed[from].includes(to)) throw new Error(`invalid refund request transition: ${from} -> ${to}`); }
export function assertRefundAmount(amount: Money, paymentAmount: Money): void { if (!Number.isFinite(amount.amount) || amount.amount <= 0) throw new Error("refund amount must be finite and positive"); if (!/^[A-Z]{3}$/.test(amount.currency)) throw new Error("refund currency must be a 3-letter uppercase code"); if (amount.currency !== paymentAmount.currency) throw new Error("refund currency mismatch"); if (amount.amount > paymentAmount.amount) throw new Error("refund amount exceeds payment amount"); }
export const RETURNS_REFUNDS_LIFECYCLE = { returns: ["REQUESTED", "APPROVED", "RECEIVED", "COMPLETED", "CANCELLED"] as const, refunds: ["REQUESTED", "APPROVED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"] as const } as const;
