export interface GatewayContext{requestId:string;correlationId:string;tenantId?:string;clientId?:string;timestamp:string;metadata?:Record<string,unknown>}
export interface RouteDefinition{id:string;name:string;version:string;path:string;methods:string[];target:string;status:'DRAFT'|'ACTIVE'|'PAUSED'|'DEPRECATED';authRequired:boolean}
export interface GatewayRequest{context:GatewayContext;protocol:'HTTP'|'HTTPS'|'WEBSOCKET'|'CUSTOM';method:string;path:string;headers:Record<string,string>;query:Record<string,string>;body?:unknown}
export interface GatewayResponse{status:number;headers:Record<string,string>;body?:unknown;requestId:string;correlationId:string}
export interface GatewayRoutePort{resolve(request:GatewayRequest):Promise<RouteDefinition|undefined>}
export interface GatewayPolicyPort{evaluate(request:GatewayRequest,route:RouteDefinition):Promise<{allowed:boolean;reason?:string}>}
export interface GatewayAuthenticationPort{authenticate(request:GatewayRequest):Promise<{authenticated:boolean;principalId?:string}>}
export interface GatewayAuthorizationPort{authorize(request:GatewayRequest,route:RouteDefinition,principalId?:string):Promise<{allowed:boolean;reason?:string}>}
export interface GatewayUpstreamPort{dispatch(request:GatewayRequest,route:RouteDefinition):Promise<GatewayResponse>}
const SENSITIVE=/(password|secret|private.?key|access.?token|refresh.?token|api.?key|authorization|bearer|cvv|cvc|pan|card.?number)/i;
export function validateMetadata(metadata?:Record<string,unknown>):void{for(const key of Object.keys(metadata??{}))if(SENSITIVE.test(key))throw new Error(`Sensitive metadata key rejected: ${key}`);}
export function validateRequest(request:GatewayRequest):void{if(!request.context.requestId||!request.context.correlationId)throw new Error('requestId and correlationId are required');if(!request.method||!request.path)throw new Error('method and path are required');validateMetadata(request.context.metadata);}
export async function handleGatewayRequest(request:GatewayRequest,deps:{routes:GatewayRoutePort;policies:GatewayPolicyPort;auth:GatewayAuthenticationPort;authorization:GatewayAuthorizationPort;upstream:GatewayUpstreamPort}):Promise<GatewayResponse>{validateRequest(request);const route=await deps.routes.resolve(request);if(!route)return {status:404,headers:{},body:{code:'ROUTE_NOT_FOUND'},requestId:request.context.requestId,correlationId:request.context.correlationId};const policy=await deps.policies.evaluate(request,route);if(!policy.allowed)return {status:403,headers:{},body:{code:'POLICY_BLOCKED',reason:policy.reason},requestId:request.context.requestId,correlationId:request.context.correlationId};let principalId:string|undefined;if(route.authRequired){const auth=await deps.auth.authenticate(request);if(!auth.authenticated)return {status:401,headers:{},body:{code:'UNAUTHORIZED'},requestId:request.context.requestId,correlationId:request.context.correlationId};principalId=auth.principalId;}const access=await deps.authorization.authorize(request,route,principalId);if(!access.allowed)return {status:403,headers:{},body:{code:'FORBIDDEN',reason:access.reason},requestId:request.context.requestId,correlationId:request.context.correlationId};return deps.upstream.dispatch(request,route);}
export const STEP_71={name:'API Gateway & Edge Delivery Foundation',version:'1.0.0',status:'FOUNDATION',providerNeutral:true} as const;
