#!/usr/bin/env bash
set -euo pipefail
BASE='https://emeriona-global.emerionaglobal.workers.dev'
T="c4-smoke-${GITHUB_RUN_ID}"; C="c4-customer-${GITHUB_RUN_ID}"; P="c4-partner-${GITHUB_RUN_ID}"; R="c4-product-${GITHUB_RUN_ID}"; O="c4-order-${GITHUB_RUN_ID}"; I="c4-item-${GITHUB_RUN_ID}"
npx wrangler d1 execute emeriona-global-db --remote --command="INSERT INTO tenants (id,name,status) VALUES ('${T}','C4 Smoke ${GITHUB_RUN_ID}','ACTIVE'); INSERT INTO customers (id,tenant_id,display_name,status) VALUES ('${C}','${T}','C4 Customer','ACTIVE'); INSERT INTO partners (id,tenant_id,legal_name,status) VALUES ('${P}','${T}','C4 Partner','VERIFIED'); INSERT INTO products (id,tenant_id,owner_id,name,status) VALUES ('${R}','${T}','${C}','C4 Product','PUBLISHED'); INSERT INTO orders (id,tenant_id,customer_id,status,total_amount,currency) VALUES ('${O}','${T}','${C}','PENDING',50,'USD'); INSERT INTO order_items (id,order_id,product_id,partner_id,quantity,unit_amount,currency) VALUES ('${I}','${O}','${R}','${P}',1,50,'USD');"
COMMON=(-H "x-tenant-id: ${T}" -H 'x-actor-id: c4-smoke' -H 'x-currency: USD' -H 'content-type: application/json')
curl -fsS "${COMMON[@]}" -H "idempotency-key: c4-payment-${GITHUB_RUN_ID}" -X POST "$BASE/api/v1/payment-intents" -d "{\"orderId\":\"${O}\",\"amount\":{\"amount\":50,\"currency\":\"USD\"}}" > payment.json
PAYMENT_ID=$(jq -r '.data.id' payment.json)
curl -fsS "${COMMON[@]}" -H "idempotency-key: c4-invoice-${GITHUB_RUN_ID}" -X POST "$BASE/api/v1/invoices" -d "{\"orderId\":\"${O}\",\"paymentIntentId\":\"${PAYMENT_ID}\",\"amount\":{\"amount\":50,\"currency\":\"USD\"}}" > invoice.json
INVOICE_ID=$(jq -r '.data.id' invoice.json)
curl -fsS "${COMMON[@]}" -H "idempotency-key: c4-settlement-${GITHUB_RUN_ID}" -X POST "$BASE/api/v1/settlements" -d "{\"orderId\":\"${O}\",\"partnerId\":\"${P}\",\"grossAmount\":{\"amount\":50,\"currency\":\"USD\"},\"commissionAmount\":{\"amount\":5,\"currency\":\"USD\"},\"netAmount\":{\"amount\":45,\"currency\":\"USD\"}}" > settlement.json
SETTLEMENT_ID=$(jq -r '.data.id' settlement.json)
curl -fsS "${COMMON[@]}" -H "idempotency-key: c4-invoice-${GITHUB_RUN_ID}" -X POST "$BASE/api/v1/invoices" -d "{\"orderId\":\"${O}\",\"paymentIntentId\":\"${PAYMENT_ID}\",\"amount\":{\"amount\":50,\"currency\":\"USD\"}}" | jq -e --arg id "$INVOICE_ID" '.data.id == $id'
curl -fsS "${COMMON[@]}" -H "idempotency-key: c4-settlement-${GITHUB_RUN_ID}" -X POST "$BASE/api/v1/settlements" -d "{\"orderId\":\"${O}\",\"partnerId\":\"${P}\",\"grossAmount\":{\"amount\":50,\"currency\":\"USD\"},\"commissionAmount\":{\"amount\":5,\"currency\":\"USD\"},\"netAmount\":{\"amount\":45,\"currency\":\"USD\"}}" | jq -e --arg id "$SETTLEMENT_ID" '.data.id == $id'
npx wrangler d1 execute emeriona-global-db --remote --command="SELECT (SELECT count(*) FROM invoices WHERE id='${INVOICE_ID}' AND status='ISSUED') invoice_ok,(SELECT count(*) FROM settlements WHERE id='${SETTLEMENT_ID}' AND status='PENDING') settlement_ok,(SELECT count(*) FROM billing_events WHERE invoice_id='${INVOICE_ID}') billing_event_ok,(SELECT count(*) FROM settlement_events WHERE settlement_id='${SETTLEMENT_ID}') settlement_event_ok,(SELECT count(*) FROM revenue_entries WHERE order_id='${O}' AND status='PENDING') revenue_ok,(SELECT count(*) FROM audit_events WHERE tenant_id='${T}' AND use_case_id='billing.invoice.create' AND outcome='SUCCEEDED') invoice_audit_ok,(SELECT count(*) FROM audit_events WHERE tenant_id='${T}' AND use_case_id='billing.settlement.create' AND outcome='SUCCEEDED') settlement_audit_ok;"
test "$(curl -sS -o /tmp/invoice-get.json -w '%{http_code}' "$BASE/api/v1/invoices")" = '405'
test "$(curl -sS -o /tmp/settlement-get.json -w '%{http_code}' "$BASE/api/v1/settlements")" = '405'
