import type { Money } from "../../domains/src/commerce.js";
import type { UseCaseHandler, UseCaseRequest, UseCaseResponse } from "./index.js";
export interface CartItemInput{readonly cartId:string;readonly productId?:string;readonly serviceId?:string;readonly quantity:number;readonly unitAmount:Money;readonly commercialOfferId?:string;}
export interface CartItemResult extends CartItemInput{readonly id:string;}
export interface CheckoutResult{readonly orderId:string;readonly cartId:string;readonly customerId:string;readonly total:Money;readonly itemCount:number;}
export interface OperationalCommercePort{addCartItem(input:CartItemInput&{id:string;tenantId:string}):Promise<CartItemResult>;checkout(input:{cartId:string;orderId:string;tenantId:string}):Promise<CheckoutResult>;}
export class AddCartItemHandler implements UseCaseHandler<CartItemInput,CartItemResult>{constructor(private readonly commerce:OperationalCommercePort,private readonly id:()=>string){}async handle(request:UseCaseRequest<CartItemInput>):Promise<UseCaseResponse<CartItemResult>>{const {cartId,productId,serviceId,quantity,unitAmount,commercialOfferId}=request.input;if((productId?1:0)+(serviceId?1:0)!==1)throw new Error("Exactly one of productId or serviceId is required");if(!Number.isFinite(quantity)||quantity<=0)throw new Error("quantity must be greater than zero");if(!Number.isFinite(unitAmount.amount)||unitAmount.amount<0)throw new Error("unitAmount must be finite and non-negative");const output=await this.commerce.addCartItem({cartId:cartId.trim(),productId,serviceId,quantity,unitAmount,commercialOfferId,id:this.id(),tenantId:request.context.tenantId});return{useCaseId:request.useCaseId,correlationId:request.context.correlationId,output};}}
export class CheckoutHandler implements UseCaseHandler<{cartId:string},CheckoutResult>{constructor(private readonly commerce:OperationalCommercePort,private readonly id:()=>string){}async handle(request:UseCaseRequest<{cartId:string}>):Promise<UseCaseResponse<CheckoutResult>>{if(!request.input.cartId.trim())throw new Error("cartId is required");const output=await this.commerce.checkout({cartId:request.input.cartId.trim(),orderId:this.id(),tenantId:request.context.tenantId});return{useCaseId:request.useCaseId,correlationId:request.context.correlationId,output};}}
export const OPERATIONAL_COMMERCE_VERSION="1.1.0" as const;
