import { createFoundationRuntime } from "../../packages/infrastructure/src/index.js";
import type { D1DatabaseLike } from "../../packages/infrastructure/src/index.js";
import type { UseCaseId, UseCaseRequest } from "../../packages/application/src/index.js";
import { createRuntimeHttpContext, validateRuntimeHttpPolicy, RUNTIME_HTTP_VERSION } from "../../packages/runtime/src/index.js";
interface AssetsBinding{fetch(request:Request):Promise<Response>};interface Env{DB:D1DatabaseLike;ASSETS:AssetsBinding}
const ROUTES:Record<string,UseCaseId>={"/api/v1/customers":"customer.create" as UseCaseId,"/api/v1/catalogs":"catalog.create" as UseCaseId,"/api/v1/products":"catalog.product.create" as UseCaseId,"/api/v1/catalog-products":"catalog.product.create.bound" as UseCaseId,"/api/v1/services":"catalog.service.create" as UseCaseId,"/api/v1/partners":"partner.create" as UseCaseId,"/api/v1/carts":"cart.create" as UseCaseId,"/api/v1/cart-items":"cart.item.add" as UseCaseId,"/api/v1/checkout":"checkout.execute" as UseCaseId,"/api/v1/orders":"order.create" as UseCaseId};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function validCurrency(value:string|null):value is string{return value!==null&&/^[A-Z]{3}$/.test(value.trim())}
export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return json({service:"emeriona-global",status:"ok",layer:"api-runtime",runtimeVersion:RUNTIME_HTTP_VERSION});if(!url.pathname.startsWith("/api/"))return env.ASSETS.fetch(request);if(request.method!=="POST")return json({error:"method_not_allowed"},405);const useCaseId=ROUTES[url.pathname];if(!useCaseId)return json({error:"not_found"},404);let runtimeContext;try{runtimeContext=createRuntimeHttpContext({request,service:"emeriona-global-api",environment:"PRODUCTION",version:RUNTIME_HTTP_VERSION});validateRuntimeHttpPolicy(request);}catch(error){return json({error:"invalid_runtime_context",message:error instanceof Error?error.message:"Invalid runtime context"},400)}const actorId=runtimeContext.actorId;if(!actorId)return json({error:"tenant_and_actor_context_required"},400);const currency=request.headers.get("x-currency");if(!validCurrency(currency))return json({error:"valid_currency_required"},400);let input:unknown;try{input=await request.json()}catch{return json({error:"invalid_json"},400)}const idempotencyKey=request.headers.get("idempotency-key")?.trim()||undefined;const foundation=createFoundationRuntime(env.DB,{tenantId:runtimeContext.tenantId,currency:currency.trim(),authorize:async requestedUseCase=>requestedUseCase===useCaseId&&actorId.length>0});const envelope:UseCaseRequest<unknown>={useCaseId,context:{tenantId:runtimeContext.tenantId as UseCaseRequest<unknown>["context"]["tenantId"],correlationId:runtimeContext.correlationId as UseCaseRequest<unknown>["context"]["correlationId"],actorId,requestId:runtimeContext.requestId,locale:runtimeContext.locale,timezone:runtimeContext.timezone,metadata:{transport:"cloudflare-worker",runtimeVersion:RUNTIME_HTTP_VERSION}},input,idempotencyKey};try{const result=await foundation.execute<unknown,unknown>(envelope);return json({data:result.output,meta:{useCaseId:result.useCaseId,correlationId:result.correlationId,requestId:runtimeContext.requestId}},200)}catch(error){return json({error:"use_case_failed",message:error instanceof Error?error.message:"Use case execution failed",correlationId:runtimeContext.correlationId,requestId:runtimeContext.requestId},400)}}};
